apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  labels:
    app: nsq
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "ping"
    prometheus.io/port: "4161"
spec:
  ports:
  - port: 4160
    # targetPort: 4160
    name: tcp
  - port: 4161
    # targetPort: 4161
    name: http
  # type: NodePort
  clusterIP: None
  selector:
    app: nsq
    component: nsqlookupd